[package]
name = "fut-test"
namespace = "fut"
version = "0.0.1"
entrypoint = "lib.typ"
authors = ["Daniel Cook"]
license = "MIT"
description = "A package containing convenience functions for creating tests for FUT."


[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
