[package]
name = "fut-test"
version = "0.1.5"
entrypoint = "lib.typ"
authors = ["Daniel Cook"]
license = "MIT"
description = "A package containing convenience functions for creating tests for FUT."


[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
